version: '3.6'

services:
  mongodb:
    image: mongo:4.4.4
    ports:
      - target: 27017
        published: 27018
        protocol: tcp
        mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin123

  mysql:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - target: 3306
        published: 8989
        protocol: tcp
        mode: host
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: pizza-app
